allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@pkgr/core'
  - napi-postinstall
  - synckit
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - sharp
  - eslint-config-prettier
