name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ers.esncz.org
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/ers
            git pull origin main
            GIT_COMMIT_SHA=${{ github.sha }} docker compose -f compose.yml build --no-cache && docker compose -f compose.yml up -d --force-recreate
